### ISSUE TITLE
array_get when not used with Laravel

### ISSUE THREAD

**Issue by speeddragon** [jonnywilliamson/tplinksmartplug#1]
Hi, I want to used you library in a PHP script without using Laravel. In the **TPLinkDevice.php** class you use **array_get** on line **81**.

I'have create a similar function to the the job of the array_get, I don't know if you can add it to the repo or if it make sense.

Thanks

**Comment by jonnywilliamson** [comment]
Ah yes. I did not notice I had used a laravel function in there. 

Do you want to send a PR and I can add it to the library?

Is the library working for you otherwise?

**Comment by speeddragon** [comment]
I can make the PR (first time!).

I want to add some information to ElasticSearch, so I will test better when everything in done and collecting data.

**Comment by jonnywilliamson** [comment]
Fixed with #2

Thanks @speeddragon
