### ISSUE TITLE
Can we use it to interact with EAP 115 Access point ?

### ISSUE THREAD

**Issue by hardevine** [jonnywilliamson/tplinksmartplug#7]

**Comment by jonnywilliamson** [comment]
I don't have one to test it with so I can't answer that, sorry.

**Comment by hardevine** [comment]
any doc or link i can refer to know more about it ?, i have inspected POST requests and COOKIE behaviour

**Comment by jonnywilliamson** [comment]
This library deals with smart plugs, not access points. I don't have any documentation for you I'm afraid.

Why not download the library and see if you can connect to whatever device you have. Might be the quickest way to test everything.
